Implement expiring api access tokens
genghisken/psat-server-web pull request #30
Opened 2024-09-23 13:53 UTC by jackleland

Builds on permissions changes in #29. 

Adds additional setting (in settings.py) and authentication model which invalidates tokens created longer ago than the set expiry time. The auth-token endpoint can be used to get a refreshed token (using a valid username and password). Utilised only existing models so no migrations required.  

This addresses the problem of an access-token getting exposed in some manner and then forever compromising the api interface.

2024-09-24 14:09 UTC, jackleland commented
This requires additional, fine grained control over the expiry of tokens for different users

2024-09-24 14:10 UTC, jackleland commented
See https://github.com/HeloiseS/atlasapiclient/issues/4

2024-10-15 10:27 UTC, jackleland commented
Fine-grained control over authentication, specifically different token expiries for different groups, is now implemented. This required a database change and so requires migrations for the feature to work as expected - I'm still working on a neat solution but this can be achieved right now through Django migrations if you run (in the container or otherwise, before pull these changes) a fake migration with 
``` bash
python manage.py makemigrations atlas
python manage.py migrate atlas --fake 
```

and then pull these changes and run the `makemigrations atlas` and `migrate atlas` again. This should then correctly make the required table `auth_group_profile`. 

This is not a neat solution right now and probably requires either a manual migration to be written or an updated init.sql file to be distributed.

2024-10-28 15:26 UTC, genghisken commented on psat_server_web/atlas/atlas/models.py
> +    map_iteration = models.CharField(max_length=100, unique=True, blank=True, null=True)
This is always requested by Django, but I don't believe it needs to be actually done. Ken to find out why!

2024-10-28 15:36 UTC, genghisken requested changes

2024-10-28 15:36 UTC, genghisken commented on psat_server_web/atlas/atlas/settings.py
> +DEBUG = True
Set back to False always for deployment reasons

2024-10-28 15:36 UTC, genghisken commented on psat_server_web/atlas/atlas/settings.py
> +TEMPLATE_DEBUG = True
Set back to False for live deployment

2024-10-28 15:48 UTC, merged